import Head from 'next/head';
import Image from 'next/image';
import Banner from '../components/Banner';
import Expriences from '../components/Expriences';
import Giftcard from '../components/Giftcard';
import Header from '../components/Header';
import InspirationCard from '../components/InspirationCard';
import QuestionBanner from '../components/QuestionBanner';
import Tabs from '../components/Tabs';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className=''>
      <Head>
        <title>
          Airbnb: Vacation Rentals, Cabins, Beach Houses, Unique Homes &amp;
          Experiences
        </title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/logo.ico' />
      </Head>

      <Header />
      <Banner />
      <Giftcard />
      <InspirationCard />
      <Expriences />
      <QuestionBanner />
      <Tabs />
    </div>
  );
}
