import Head from 'next/head';
import Banner from '../components/Banner';
import Expriences from '../components/Expriences';
import Giftcard from '../components/Giftcard';
import Header from '../components/Header';
import InspirationCard from '../components/InspirationCard';
import QuestionBanner from '../components/QuestionBanner';
import BasicTabs from '../components/BasicTabs';
import Header2 from '../components/subcomponents/Header2';

export default function Home() {
  return (
    <div className=''>
      <Head>
        <title>
          Airbnb: Vacation Rentals, Cabins, Beach Houses, Unique Homes &amp;
          Experiences
        </title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/logo.ico' />
      </Head>

      <Header />
      <Header2 />
      <Banner />
      <Giftcard />
      <InspirationCard />
      <Expriences />
      <QuestionBanner />
      <BasicTabs />
    </div>
  );
}
